name: Linux
on:
  push:
    branches-ignore:
      - '**/windows/**'
      - '**/macos/**'
  pull_request:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, '/debian/') }}
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: wxFormBuilder.flatpak
        manifest-path: install/linux/org.wxformbuilder.wxFormBuilder.json
        cache-key: flatpak-builder-${{ github.sha }}
  debian:
    name: Debian Package
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, '/flatpak/') }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup environment
      run: |
        sudo apt install libwxgtk3.0-gtk3-dev libwxgtk-media3.0-gtk3-dev libboost-dev debhelper fakeroot
    - name: Create build system
      if: ${{ false }}
      run: |
        cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release -DWXFB_WXWIDGETS_ENABLE_30=ON
    - name: Package build system
      if: ${{ false && (contains(github.ref, '/test_') || contains(github.ref, '/test/')) }}
      run: |
        zip -ry wxFormBuilder-Linux-build.zip _build
    - name: Build
      if: ${{ false }}
      run: |
        cmake --build _build --config Release -j `nproc`
        cmake --install _build --config Release
    - name: Test
      if: ${{ false }}
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          _install/bin/wxformbuilder -g wxfbTest/wxfbTest.fbp
    - name: Package deb
      run: |
        cp -rf install/linux/deb/ ./debian/
        dpkg-buildpackage --build=binary --no-sign --root-command=fakeroot --jobs=auto
    - uses: actions/upload-artifact@v2
      with:
        name: Debian Package
        path: |
          wxFormBuilder-Linux-build.zip
          ../*.deb
