name: Linux
on:
  push:
    branches-ignore:
      - '**/windows/**'
      - '**/macos/**'
  pull_request:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: wxformbuilder.flatpak
        manifest-path: install/linux/org.wxformbuilder.wxFormBuilder.json
        cache-key: flatpak-builder-${{ github.sha }}
