name: macOS
on:
  push:
    branches-ignore:
      - '**/windows/**'
      - '**/linux/**'
  pull_request:

jobs:
  bundle:
    name: App Bundle
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-11]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Fetch tags
      run: |
        git fetch --prune --depth=1 --tags --no-recurse-submodules
    - name: Setup environment
      run: |
        brew update
        brew install cmake make wxwidgets boost
    - name: Create build system
      run: |
        cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release
    - name: Package build system
      if: ${{ contains(github.ref, '/build/') }}
      run: |
        zip -ry wxFormBuilder-macOS-build.zip _build
    - name: Build
      run: |
        cmake --build _build --config Release -j `sysctl -n hw.ncpu`
        cmake --install _build --config Release
    - name: Test
      run: |
        _install/wxFormBuilder.app/Contents/MacOS/wxFormBuilder -v
        _install/wxFormBuilder.app/Contents/MacOS/wxFormBuilder -g wxfbTest/wxfbTest.fbp
    - name: Package app bundle
      run: |
        cd _install
        zip -ry ../wxFormBuilder-macos-`sw_vers -productVersion | cut -d . -f 1-2`-`uname -m`-bundle.zip wxFormBuilder.app
    - uses: actions/upload-artifact@v2
      with:
        name: App Bundle ${{ matrix.os }}
        path: |
          wxFormBuilder-macOS-build.zip
          wxFormBuilder-*-bundle.zip
