name: Sources
on:
  push:
    branches:
      - '**/sources/**'
    tags:
      - v*

jobs:
  windows:
    name: Windows line endings
    runs-on: windows-latest
    steps:
    - uses: actions/github-script@v5
      id: variables
      with:
        result-encoding: string
        script: |
          return context.ref.split('/').pop().slice(1)
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        release: false
        update: false
        install: >-
          mingw-w64-x86_64-libzip
          git
    - name: Create source archive
      shell: msys2 {0}
      run: |
        git archive "--output=wxFormBuilder-${{ steps.variables.outputs.result }}-source-full.zip" "--prefix=wxFormBuilder-${{ steps.variables.outputs.result }}/" HEAD
        git submodule foreach --recursive 'git archive --output=module.zip "--prefix=wxFormBuilder-${{ steps.variables.outputs.result }}/$sm_path/" HEAD && zipmerge "$toplevel/wxFormBuilder-${{ steps.variables.outputs.result }}-source-full.zip" module.zip && rm -f module.zip'
    - uses: actions/upload-artifact@v2
      with:
        name: wxFormBuilder Source (CRLF)
        path: |
          *-source-full.zip
  linux:
    name: Linux line endings
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v5
      id: variables
      with:
        result-encoding: string
        script: |
          return context.ref.split('/').pop().slice(1)
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Create source archive
      run: |
        git archive "--output=wxFormBuilder-${{ steps.variables.outputs.result }}-source-full.tar" "--prefix=wxFormBuilder-${{ steps.variables.outputs.result }}/" HEAD
        git submodule foreach --recursive 'git archive --output=module.tar "--prefix=wxFormBuilder-${{ steps.variables.outputs.result }}/$sm_path/" HEAD && tar -Af "$toplevel/wxFormBuilder-${{ steps.variables.outputs.result }}-source-full.tar" module.tar && rm -f module.tar'
        gzip "wxFormBuilder-${{ steps.variables.outputs.result }}-source-full.tar"
    - uses: actions/upload-artifact@v2
      with:
        name: wxFormBuilder Source (LF)
        path: |
          *-source-full.tar.gz
