name: Windows
on:
  push:
    branches-ignore:
      - '**/linux/**'
      - '**/macos/**'
  pull_request:

jobs:
  installer:
    name: Installer
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw32, env: i686 }
          - { sys: mingw64, env: x86_64 }
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Fetch tags
      shell: cmd
      run: |
        git fetch --prune --depth=1 --no-recurse-submodules
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        release: false
        update: true
        install: >-
          mingw-w64-${{ matrix.env }}-toolchain
          mingw-w64-${{ matrix.env }}-cmake
          mingw-w64-${{ matrix.env }}-make
          mingw-w64-${{ matrix.env }}-wxWidgets3.1
          mingw-w64-${{ matrix.env }}-boost
          base-devel
          git
    - name: Create build system
      shell: msys2 {0}
      run: |
        cmake -S . -B _build -G "MSYS Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release
    - name: Package build system
      if: ${{ contains(github.ref, '/build/') }}
      shell: cmd
      run: |
        7z a -tzip -r -bb1 wxFormBuilder-Windows-build.zip _build
    - name: Build
      shell: msys2 {0}
      run: |
        cmake --build _build --config Release -j `nproc`
        cmake --install _build --config Release
    - name: Test
      shell: cmd
      run: |
        _install\\wxFormBuilder.exe -v
        _install\\wxFormBuilder.exe -g wxfbTest\\wxfbTest.fbp
    - name: Create installer
      shell: cmd
      run: |
        ISCC.exe /DArch=${{ matrix.env }} /O. install\\windows\\wxFormBuilder.iss
    - uses: actions/upload-artifact@v2
      with:
        name: Windows Installer ${{ matrix.env }}
        path: |
          wxFormBuilder-Windows-build.zip
          wxFormBuilder-*.exe
