name: Windows
on: [push, pull_request]

jobs:
  installer:
    name: Installer
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        release: false
        update: false
        install: 'mingw-w64-i686-gcc mingw-w64-i686-wxWidgets3.1 cmake make'
    - name: Create build system
      shell: msys2 {0}
      run: |
        cmake -S . -B _build -G "MSYS Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release
    - name: Package build system
      if: ${{ startsWith(github.ref, 'refs/heads/test_') }}
      shell: cmd
      run: |
        7z a -tzip -r wxFormBuilder_Windows_build.zip _build
    - name: Build
      shell: msys2 {0}
      run: |
        cmake --build _build --config Release -j `nproc`
        cmake --install _build --config Release
    - name: Test
      shell: msys2 {0}
      run: |
        _install/wxFormBuilder.exe -g wxfbTest\\wxfbTest.fbp
    - name: Create installer
      shell: cmd
      run: |
        ISCC.exe /O. install\\windows\\wxFormBuilder.iss
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows Installer
        path: |
          wxFormBuilder_Windows_build.zip
          wxFormBuilder-*.exe
