name: Windows
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Installer
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        release: false
        update: false
        install: 'gcc wxWidgets3.1 cmake make'
    - name: Build
      shell: msys2 {0}
      run: |
        cmake -S . -B build -G "MSYS Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j `nproc`
        cmake --install build
    - name: Create installer
      shell: cmd
      run: '"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" install/windows/wxFormBuilder.iss'
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows Installer
        path: install\windows\wxFormBuilder-*.exe
